version: "3.8"

services:
  app:
    build:
      context: .  # Build the app using the current directory
      dockerfile: Dockerfile  # Use the Dockerfile for building
    image: flask-app:latest  # Tag the built image with a name
    ports:
      - "5000:5000"  # Map the container port to host port
    depends_on:
      - db  # Ensure db starts before the app
    environment:
      - FLASK_APP=app.py  # Set the FLASK_APP environment variable
      - FLASK_ENV=development  # Set Flask environment for development

  db:
    image: postgres:13  # Use the official postgres image
    environment:
      POSTGRES_USER: flaskuser  # PostgreSQL user
      POSTGRES_PASSWORD: flaskpassword  # PostgreSQL password
      POSTGRES_DB: flaskdb  # Database name
    ports:
      - "5432:5432"  # Expose Postgres port
