version: "3.8"

services:
  app:
    image: flask-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: flaskuser
      POSTGRES_PASSWORD: flaskpassword
      POSTGRES_DB: flaskdb
    ports:
      - "5432:5432"
